Add changes to lists and names
azavea/terraform-aws-redis-elasticache pull request #8
Opened 2016-10-31 14:41 UTC by myoung34

2016-11-01 23:18 UTC, hectcastro requested changes
Thanks for taking the time to contribute these changes, @myoung34.

2016-11-01 23:18 UTC, hectcastro commented on main.tf
> +  security_group_ids   = "${var.security_group_ids}"
Can you please add this to the `README`?

2016-11-01 23:18 UTC, hectcastro commented on main.tf
> +  # for some reason trying to pass a list here causes the error `  * aws_cloudwatch_metric_alarm.cpu: alarm_actions: should be a list` in terraform 0.7.5
Is this happening because the variable isn't defined as type `list`?

2016-11-01 23:18 UTC, hectcastro commented on outputs.tf
> -output "cache_security_group_id" {
Can you please remove this from the `README`?

2016-11-08 02:07 UTC, myoung34 commented on main.tf
> +  # for some reason trying to pass a list here causes the error `  * aws_cloudwatch_metric_alarm.cpu: alarm_actions: should be a list` in terraform 0.7.5
I think it might be a bug. Even defining it as a list causes the apply to fail

2016-11-08 02:09 UTC, myoung34 commented on main.tf
> +  security_group_ids   = "${var.security_group_ids}"
done

2016-11-08 02:09 UTC, myoung34 commented on outputs.tf
> -output "cache_security_group_id" {
done

2016-11-14 15:21 UTC, hectcastro commented
Apologies for the slow turnaround time.

We recently had to build out a Redis ElastiCache cluster for a new project and encountered the [elasticache_replication_group](https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html) Terraform resource. For Redis, this seems a lot more desirable than the more primitive `aws_elasticache_cluster` resource because it optionally helps wire up a hot-standby.

Moving forward, we want to change this module to make use of the `elasticache_replication_group` resource. I'd like to merge this PR, but not cut another release until the `elasticache_replication_group` change is made, and then cut a release that increments the major version number.

2016-11-14 15:21 UTC, hectcastro approved these changes

2016-11-14 15:21 UTC, merged

2016-11-14 15:22 UTC, myoung34 commented
No worries, I'm not dependent on it any longer, just wanted to submit some things I found. Thanks!